### ISSUE TITLE
[Issue]: different/inconsistent python interfaces 

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [RadeonOpenCompute/amdsmi#11]
### Problem Description

The python interface functions are different depending on rocm version, is there a reason they're not updated for all rocm versions ?
rocm5.7: `devices_handles = amdsmi.amdsmi_get_processor_handles()`
rocm5.6: `devices_handles = amdsmi.amdsmi_get_device_handles()`

my problem is that I have to do things like this to support each version of rocm 😅
https://github.com/huggingface/optimum-benchmark/blob/main/optimum_benchmark/launchers/isolation_utils.py#L65-L111

### Operating System

Ubuntu 22.04

### CPU

AMD Epyc

### GPU

AMD Instinct MI250

### ROCm Version

ROCm 5.7.0, ROCm 5.6.0

### ROCm Component

amdsmi

**Comment by marifamd** [comment]
Hi @IlyasMoutawwakil thank you for reaching out. You are correct, we did change this because amd-smi will be able to handle all amd processors (GPUs & CPUs) in the future. 

amd-smi is still a realtively new project and I'm excited to see developers use the python library that we developed. FYI we are aware of the bugs in the amdsmi_get_gpu_process_list & amdsmi_get_gpu_process_info functions as we are redesigning it.

**Comment by harkgill-amd** [comment]
Hi @IlyasMoutawwakil, thank you again for reaching out with your concerns. Following up on @marifamd's reply, it looks like the function has not changed from `amdsmi_get_processor_handles()` since ROCm 5.7. As a result, I will close out this issue.
